[package]
name = "turbine_vis"
version = "0.1.0"
edition = "2021"

[workspace]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "turbine_vis"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.24.0"
