# pinned threads that do very important stuff
[native_configs.solPohTickProd]
max_threads = 1
core_allocation.PinnedCores = { min = 0, max = 1 }

[native_configs.solSigVerTpu]
max_threads = 1
core_allocation.PinnedCores = { min = 1, max = 2 }

[native_configs.solSigVerTpuVote]
max_threads = 1
core_allocation.PinnedCores = { min = 2, max = 3 }

[native_configs.solGossip]
max_threads = 16
core_allocation.DedicatedCoreSet = { min = 16, max = 64 }

[native_configs.solRepair]
max_threads = 16
core_allocation.DedicatedCoreSet = { min = 16, max = 64 }

[native_configs.FetchStage]
max_threads = 16
core_allocation.DedicatedCoreSet = { min = 16, max = 64 }

[native_configs.solShredFetch]
max_threads = 16
core_allocation.DedicatedCoreSet = { min = 16, max = 64 }


[rayon_configs.solReplayTx] #Replay transactions pool
worker_threads = 8

[rayon_configs.solReplayFork] # Replay forks pool
worker_threads = 16

[rayon_configs.solRayonGlob] # this is not used!
worker_threads = 1
stack_size_bytes = 100                                    # bytes because we want this to crash!
core_allocation.DedicatedCoreSet = { min = 63, max = 64 }

[rayon_configs.solRunGossip] #
worker_threads = 4

[rayon_configs.solGossipWork]
worker_threads = 8

[rayon_configs.solGossipCons] # Gossip Consume
worker_threads = 12

[rayon_configs.solAccounts] # AccountsDb foreground threads
worker_threads = 4

stack_size_bytes = 8388608                                # 8 megabytes
core_allocation.DedicatedCoreSet = { min = 16, max = 64 }

[rayon_configs.solAccountsLo] # AccountsDb backkground
worker_threads = 4
stack_size_bytes = 8388608                                # 8 megabytes
core_allocation.DedicatedCoreSet = { min = 16, max = 64 }

[rayon_configs.solAcctHash] # AccountsDb hash pool
worker_threads = 4
core_allocation.DedicatedCoreSet = { min = 16, max = 64 }


# Networking runtimes (tokio)
[tokio_configs.solQuicClientRt]
worker_threads = 4
core_allocation.DedicatedCoreSet = { min = 16, max = 64 }

[tokio_configs.solQuicTVo]
worker_threads = 4
core_allocation.DedicatedCoreSet = { min = 16, max = 64 }

[tokio_configs.solQuicTpu]
worker_threads = 4
core_allocation.DedicatedCoreSet = { min = 16, max = 64 }

[tokio_configs.solQuicTpuFwd]
worker_threads = 4
core_allocation.DedicatedCoreSet = { min = 16, max = 64 }

[tokio_configs.solRepairQuic]
worker_threads = 8
core_allocation.DedicatedCoreSet = { min = 16, max = 64 }

[tokio_configs.solGossipQuic]
worker_threads = 8
core_allocation.DedicatedCoreSet = { min = 16, max = 64 }

[tokio_configs.solTurbineQuic]
worker_threads = 8
core_allocation.DedicatedCoreSet = { min = 16, max = 64 }

# everything else
default_core_allocation.DedicatedCoreSet = { min = 5, max = 64 }
