[package]
name = "wf-common"
version = "0.1.0"
edition = "2021"

[features]
default = []
user = ["aya"]
bpf=["aya-ebpf"]

[dependencies]
network-types = "0.0.7"
aya = { version = "0.13", optional = true }
aya-ebpf = { version="0.1", optional = true }

[lib]
path = "src/lib.rs"
